name: Deploy Deno

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Asia/Shanghai

permissions:
  id-token: write 
  contents: read 

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: Pull latest repository
      uses: actions/checkout@v2

    - name: Setup Node.js latest
      uses: actions/setup-node@main
      with:
        node-version: "latest"

    - name: Setup Deno 
      uses: denoland/setup-deno@v1 
      with:
        deno-version: "1.46.x"

    - name: Install deployctl
      run: deno install -Arf jsr:@deno/deployctl

    - name: Install dependencies
      run: | 
        npm install
        deno cache server.ts 

    - name: Get rss.json
      run: | 
        node link.js

    - name: Deploy using Deploy Token 
      run: |
        deployctl deploy --project=szn-friends --token=$DENO_DEPLOY_TOKEN server.ts
      env:
        DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
