name: Deploy Deno

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Asia/Shanghai

permissions:
  id-token: write 
  contents: read 

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: Pull latest repository
      uses: actions/checkout@v2

    - name: Setup Node.js latest
      uses: actions/setup-node@main
      with:
        node-version: "latest"

    - name: Setup Deno 
      uses: denoland/setup-deno@v1 
      with:
        deno-version: "1.40.x"

    - name: Install deployctl
      run: deno install -A -r https://deno.land/x/deploy/deployctl.ts 

    - name: Install dependencies
      run: | 
        npm install
        deno cache server.ts 

    - name: Get rss.json
      run: | 
        node link.js

    - name: Deploy using Deploy Token 
      run: |
        deployctl deploy --project=szn-friends --token=$DENO_DEPLOY_TOKEN server.ts
      env:
        DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 30
        keep_minimum_runs: 6

  keepalive-workflow:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: check_links
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"